### ISSUE TITLE
Run trajectory_points_act_server do nothing

### ISSUE THREAD

**Issue by chauthehan** [dvalenciar/robotic_arm_environment#4]
Thank you for your work. I have successfully do all the steps except the last one. When I run  `ros2 run my_doosan_pkg trajectory_points_act_server`,  the terminal show nothing, and the robot in gazebo stay still. Do you know what happen?
My os: ubuntu 20
Ros version: ros foxy

**Comment by chauthehan** [comment]
It's turns out my action server is not working, the variable `self.server_is_ready()` is always return False. I don't know what happen here

**Comment by tanmay2798** [comment]
Did you solve the issue?

**Comment by zorx01** [comment]
In the launch files inside the my_doosan_pkg in the section were we load and start the controllers change the '--set-state' flag to active instead of start.

**Comment by dvalenciar** [comment]
Thanks, @zorx01. It seems that fixed the issue. Closing this issue
