### ISSUE TITLE
How many times do you need to train the robot arm to reach the target position well?

### ISSUE THREAD

**Issue by hyungtai-kim** [dvalenciar/robotic_arm_environment#5]
It is very helpful to experience reinforcement learning simulation using your examples.
I'm running through your examples, but it's hard to see that reinforcement learning is working.
How many times can you tell if you've reached 80% of your target?

**Comment by dvalenciar** [comment]
Currently, there is no way to reach the goal now since it is taking random action. Soon I will implement some RL algorithms as TD3 or SAC, to solve the task
What you have now is just the environment
